config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  
  resources :searches
  resources :auctions
  resources :auctions do
    member do
      patch 'claim'
    end
  end

  root 'auctions#index'
  # patch '/auctions/:id/claim', to: 'auctions#claim'

  resources :users, only: [:index, :show]
  get 'claimed', to: 'users#claimed'
  get 'sold', to: 'users#sold'

  resources :bids, only: [:index, :new, :create]
  get 'cart', to: 'bids#cart'
  
  # get 'show', to: 'users#show'
  # get 'index', to: 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :auction


end

app/controllers/bids_controller.rb
class BidsController < ApplicationController 
    before_action :authenticate_user!
    before_action :set_bid, only: []
    
    # Requests: GET
    def index #show all bids assosiated to a specific product/auction
        @auction = Auction.find(params[:id])
        @bids = Bid.where(auction: @auction)
    end    
    
    # Requests: GET
    def cart #show all the product in which current user has done bidding
        # @auction = Auction.find(params[:auction_id])
        @bids = Bid.where(user: current_user)
    end

    # Requests: GET
    def new
        @bid = Bid.new
        @id = params[:id]
        # @auction = Auction.find(params[:id])
        # @id = params.dig(:new, :id) 
    end

    # # Requests: GET
    # def edit
    # end

    # after new create action POST and takes care of submmition
    # Requests: POST
    def create
        @auction = Auction.find(params[:auction_id])
        
        @bid = Bid.new(@bid_params)
        @bid.amount = params[:bid][:amount]

        if ( @auction != nil and @bid.amount != nil and can_vote?(@auction.id, @bid.amount) )
            @bid.user = current_user
            @bid.auction_id = @auction.id
            @auction.bidder = current_user.id
            @auction.current_price = @bid.amount
            @auction.save
            # print "check" + params[:auction_id]
            # print params[:bid][:amount]
            
            respond_to do |format|
                if @bid.save
                    format.html { redirect_to bids_path(:id => @auction.id), success: 'Bid was successfully created.' }
                    # redirect_to user(current_user)
                    # :success 'Bid was successfully created.'
                else
                    format.html { redirect_to auction_path(@auction), danger: 'Something went wrong Bid not created!' }
                    # render 'new'
                    # :danger 'Something went wrong Bid not created!'  
                end
            end
        else
            respond_to do |format|
            format.html { redirect_to auction_path(@auction), info: 'You can not bid less than current price or no your own products' }
        end
    end


    # after edit update action PATCH /PUT and takes care of submmition 
    # Requests: Patch/Put 
    # def update
    #     if @bid.update(bid_params)
    #         redirect_to user_path(current_user)
    #         # :success 'Bid is updated successfully'
    #     else
    #         render 'edit'
    #         # :info 'Bid could not be updated'
    #     end
    # end

# private

        def set_bid
            @bid = Bid.find(params[:id])
        end
        
        def bid_params
            params.require(:bid).permit(:amount, :auction_id, :id)
        end
        
    end
end

app/views/bids/_form.html.erb
<div class="row" style="margin:3rem;">
    <div class="col-sm-offset-2 col-xs-8">
        <%= form_with(model: bid, local: true) do |form| %>
        <%= render "devise/shared/error_messages", resource: bid %>

            <div class="form-group">
                <%= form.label :Time_to_bid  %>
                <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
                <div class="input-group">
                <div class="input-group-addon">&#x20B9;</div>
                    <%= form.number_field :amount, class: "form-control", placeholder: "Enter Amount", autofocus: true %>
                <div class="input-group-addon">.00</div>
                </div>
            </div>

            <div>
                <%= hidden_field_tag "auction_id", @id %>
            </div>


            <div class="form-group center">
                <button class="btn btn-primary btn-md" data-toggle="tooltip" data-placement="left" title="bid more than current price">
                    Create Bid<% form.submit %>
                </button>                
                <%= link_to 'Back', :back ? :back : auctions_path, class: "btn btn-default btn-md" %>
            </div>

        <% end %>
    </div>
</div>

app/views/bids/cart.html.erb
<div class="list-group">
  <div class="list-group-item selected">
    <h4 class="list-group-item-heading">cart, these are the product in which you have done bidding</h4>
  </div>
</div>

<% @bids.map(&:auction).uniq.each do |auction| %>
    <% if !auction.buyer_id %>
        <div class="row thumbnail user-show-page" style="padding: 0px;">
            
            <div class ="col-sm-12 col-md-7 "style="padding: 0px;">
                <% if auction.image.attached? %>
                    <%= image_tag(auction.image, style: "width: 100%; height:41rem") if auction.image.attached? %>
                <% else %>
                    <div class ="col-xs-12 col-md-4 "style= "width:100%; height:41rem; background-color:#f4f4f4">
                        <div class="no-image-massage"> 
                            No Image Available
                        </div>
                    </div>
                <% end %>
            </div>

            <div class= "col-sm-12 col-md-5 ">
                <h2 class="center"><%= auction.name %></h2>
                <h3>STARTING BID: <%= auction.starting_bid %> &#x20B9;<br> CURRENT PRICE: <%= auction.current_price %> &#x20B9;</h3> 
                
                <h3>Description</h3>
                <p><%= truncate(auction.description, :ommision => "... Read More", :length => 150) %></p>
                
                <h3>
                    <% if in_progress?(auction.id) %> 
                        Deadline in: <%= time_ago_in_words(auction.deadline) %>
                    <% else %>
                        <small>Deadline was: <%= auction.deadline.strftime("%B %d, %Y | %l:%M %p") %></small>
                    <% end %>
                </h3>
                <p></p><br><br>

                <% if in_progress?(auction.id) %>
                    <%= link_to 'Bid Now', new_bid_path(:id => auction.id), class: "btn btn-sm btn-primary" %> 
                <% else %>
                    <% if auction.bidder == current_user.id %>
                        <%= link_to 'Claim Product', claim_auction_path(auction.id), method: :patch, class: "btn btn-sm btn-primary"%>
                    <% end %>
                <% end %>

                    <%= link_to 'Products Details', auction, class:"btn btn-sm btn-default" %> 
                    <%= link_to 'All bids', bids_path(:id => auction.id), class: "btn btn-sm btn-default"%>

                <small> <br>
                    [ owner:<strong> <%= auction.user.full_name if auction.user %> </strong> ]  
                    <% if auction.bidder %>  
                            [ current bidder: <strong> <%=  User.find(auction.bidder).full_name %></strong>
                    <% else %> 
                            [ claimed by: <strong>Not yet claimed</strong>
                    <% end %> ] <br>     
                    added for auction: <%= time_ago_in_words(auction.created_at)%> ago,
                    last updated: <%= time_ago_in_words(auction.updated_at) %> ago 
                </small>
            </div>
        </div>
    <% end %>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', :back %>

app/views/bids/index.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
  </div>
<% end %>

<div class= "col-xs-12 col-md-5 ">
    
    <div class="row thumbnail" style="padding: 0px;">
        <div class ="col-xs-12 col-md-12 "style="padding: 0px;">
            <% if @auction.image.attached? %>
                <%= image_tag(@auction.image, style: "width: 100%;") if @auction.image.attached? %>
            <% else %>
                <div class ="col-xs-12 col-md-4 "style= "width:100%; height:30rem; background-color:#f4f4f4">
                    <div class="no-image-massage"> 
                        No Image Available
                    </div>
                </div>
            <% end %>
        </div>
        <div class= "col-xs-12 col-md-12 ">
            <h2 class="center"><%= @auction.name %></h2>
            <h3>STARTING BID: <%= @auction.starting_bid %> &#x20B9; <br> CURRENT PRICE: <%= @auction.current_price %> &#x20B9;</h3> 
            
            <h3>Description</h3>
            <p><%= @auction.description%></p>
            
            <h3>
                <% if in_progress?(@auction.id) %> 
                    Auction ends in: <strong><%= time_ago_in_words(@auction.deadline) %></strong>
                <% else %>
                    Deadline was: <%= @auction.deadline.strftime("%B %d, %Y | %l:%M %p") %>
                <% end %>
            </h3>
            <br>
            
            <% if user_signed_in? && current_user == @auction.user %>
                <%= link_to 'Edit the Details', edit_auction_path(@auction), class:"btn btn-sm btn-primary " %>
                <%= link_to 'Delete the product', auction_path(@auction), method: :delete, data:{confirm: "Are you sure?"}, class:"btn btn-sm btn-danger" %>
                <%= link_to 'Back to User Dashboard', user_path(current_user), class:"btn btn-sm btn-default" %>
                <%= link_to 'Back', :back, class:"btn btn-sm btn-default " %>
            <% end %>

            <% if @auction.user != current_user %>
                <%= link_to 'Back to Home', auctions_path, class:"btn btn-sm btn-success" %>
                <%= link_to 'Bid Now', new_bid_path(:id => @auction.id), class:"btn btn-sm btn-success" %>
                <%= link_to 'Back', :back, class: "btn btn-sm btn-default"%>
            <% end %><br>
            <small>last updated: <%= time_ago_in_words(@auction.updated_at) %> ago </small>
        </div>
    </div>

    <p>Seller Details </p>
    <h2><%= link_to @auction.user.full_name, @auction.user == current_user && user_signed_in? ? user_path(@auction.user) : '#'%></h2>
    <small> 
        joined Online-Auction: <%= time_ago_in_words(@auction.user.created_at)%> ago,
        last updated: <%= time_ago_in_words(@auction.user.updated_at) %> ago 
    </small>
    
    <h3>email address</h3>
    <p><%= @auction.user.email%></p>

    <h3>contact number</h3>
    <p><%= @auction.user.contact_number%></p>
    
    <h3>address</h3>
    <p><%= @auction.user.address%></p>
</div>

<div class= "col-xs-12 col-md-7 ">
     <table class="table table-striped">
            <tr>
                <% count = 0 %>
                <th>#</th>
                <th>Bidder Name</th>
                <th>Amount</th>
                <th>Bidding Time</th>
                <th>Bidder Contact</th>
            </tr>
            <% @bids.each do |bid| %>
                <tr>
                    <td><strong> <%= count = count + 1 %> </strong></td>
                    <td><%= bid.user.full_name%></td>
                    <td><%= bid.amount ? bid.amount : '-------'%></td>
                    <td><%= bid.created_at.strftime("%B %d, %Y | %l:%M %p")%></td>
                    <td><%= bid.user.contact_number %></td>
                </tr>
            <% end %>
    </table>
</div>

app/views/bids/new.html.erb
<h1 class = "center">New Bidding</h1>

<%= render 'form', bid: @bid %>