config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  
  resources :searches
  resources :auctions
  resources :auctions do
    member do
      patch 'claim'
    end
  end

  root 'auctions#index'
  # patch '/auctions/:id/claim', to: 'auctions#claim'

  resources :users, only: [:index, :show]
  get 'claimed', to: 'users#claimed'
  get 'sold', to: 'users#sold'

  resources :bids, only: [:index, :new, :create]
  get 'cart', to: 'bids#cart'
  
  # get 'show', to: 'users#show'
  # get 'index', to: 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/auction.rb
class Auction < ApplicationRecord
    belongs_to :user
    has_many :bids #many to many assosiation 
    has_one_attached :image

    def claimed_product
        return self.buyer_id != null
    end

    def create_auction(current_user)
        self.user = current_user
        self.current_price = self.starting_bid
    end

    def set_buyer(id)
        self.buyer_id = id
    end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_auction, only: [:show, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all.order(created_at: :desc)
    # newer products first
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)
    @auction.create_auction(current_user)
    
    # @auction.user = current_user
    # @auction.current_price = @auction.starting_bid
    
    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, success: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  def claim
    @auction = Auction.find(params[:id])
    @auction.set_buyer(current_user.id)
    
    # @auction.buyer_id = current_user.id
    # print "check 1 2 3 " + @auction.buyer_id 
    # print "1 2 3 check"
      
    respond_to do |format|
      if @auction.save
        # print "check 1 2 3 " + @auction.name
          format.html { redirect_to @auction, success: 'you have successfully claimed the product!!' }
      else
          format.html { redirect_to @auction, danger: 'Somthing went wrong!!' }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, success: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, danger: 'Product is successfully removeld from auction.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def auction_params
      params.require(:auction).permit(:name, :description, :category, :starting_bid, :deadline, :bidder, :current_price, :image)
    end
  
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<div class="row" style="margin:3rem;">
    <div class="col-sm-offset-2 col-xs-8">
      <%= form_with(model: auction, local: true) do |form| %>
        <%= render "devise/shared/error_messages", resource: auction %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control", placeholder: "Enter name of product" %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control", placeholder:"Enter description" %>
        </div>

        <div class="form-group">
          <%= form.label :category %>
          <%= form.text_field :category, class: "form-control", placeholder: "Enter category of product" %>
        </div>

        <div class="form-group">
          <%= form.label :starting_bid %>
          <%= form.text_field :starting_bid, class: "form-control", placeholder:"Enter min reserve price" %>
        </div>

        <div class="form-group">
          <%= form.label :deadline %>
          <%= form.datetime_select :deadline, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :image %>
          <%= form.file_field :image, class: "form-control" %>
        </div>

        <div class="form-group center"style="margin-top:3rem;">
          <%= form.submit class: "btn btn-primary btn-md"%> 
        </div>
        <div class= "center">
          [ <%= link_to 'Show', @auction %> | <%= link_to 'Back', :back %> ]
        </div>
      <% end %>
    </div>
</div>

app/views/auctions/edit.html.erb
<div class="list-group selected">
  <a href="#" class="list-group-item">
    <h3 class="list-group-item-heading center">Editing product</h3>
  </a>
</div>

<%= render 'form', auction: @auction %>

app/views/auctions/index.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
  </div>
<% end %>

<div class="list-group selected">
  <a href="#" class="list-group-item">
    <h2 class="list-group-item-heading">Products for Auction</h2>
  </a>
</div>
<% if @auctions.any? %>
  <% @auctions.each do |auction| %>
    <% if true %> 
    <!--auction.user != current_user-->
        <div class="col-sm-6 col-md-4 "style="padding:0rem;">
          <div class="thumbnail home-page-touchup">
            
            <% if auction.image.attached? %>
                <%= image_tag(auction.image, style:"height:24.1rem; width:100%") if auction.image.attached? %>
            <% else %>
                <div class ="col-xs-12 col-md-12 "style= "width:100%; height:24.1rem; background-color:#f4f4f4">
                    <div class="no-image-massage"> 
                        No Image Available
                    </div>
                </div>
            <% end %>
            
            <div class="caption">
              <h4 class="center">
                <small>STARTING BID:</small> <%= auction.starting_bid %> &#x20B9; <br> 
                <small>CURRENT PRICE:</small> <%= auction.current_price %> &#x20B9;<br>
                <% if auction.bidder.nil? %>
                  <small>No bidding found </small>                
                <% else %>
                  <small>CURRENT BIDDER:</small> <%= get_user(auction.bidder).full_name%>
                <% end %>
              </h4>
              <h3 class="center"><%= auction.name %></h3>
              <p class="center"><%= truncate(auction.description, :ommision => ".... Read More", :length => 150) %></p>
              
              <p class="center">
                <%= link_to 'Bid Now', new_bid_path(:id => auction.id), class: "btn btn-sm btn-primary" %> 
                <%= link_to 'Products Details', auction, class:"btn btn-sm btn-default" %> 
                <%= link_to 'All bids', bids_path(:id => auction.id), class: "btn btn-sm btn-default"%> 
              </p>
      
                <small>    
                    added for auction: <%= time_ago_in_words(auction.created_at)%> ago
                </small>
                <h4>
                  <% if in_progress?(auction.id) %> 
                    auction ends in: <strong><%= time_ago_in_words(auction.deadline) %></strong>
                  <% else %>
                    Deadline was: <%= auction.deadline.strftime("%B %d, %Y | %l:%M %p") %>
                  <% end %>
                </h4>
    
            </div>
          </div>
        </div>
    <% end %>
  <% end %>
<% else %>
<div class="caption">
  <h4 class="center">
  No auction item found!
</div>
<% end %>

app/views/auctions/new.html.erb
<div class="list-group selected">
  <a href="#" class="list-group-item">
    <h3 class="list-group-item-heading center">Add new product for auction</h3>
  </a>
</div>

<%= render 'form', auction: @auction %>

app/views/auctions/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"> 
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> 
    <%= value %>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
  </div>
<% end %>

<div class="row thumbnail" style="padding: 0px;">
    <div class ="col-xs-12 col-md-7 "style="padding: 0px;">
        <% if @auction.image.attached? %>
            <%= image_tag(@auction.image, style: "width: 100%; height:40rem") if @auction.image.attached? %>
        <% else %>
            <div class ="col-xs-12 col-md-4 "style= "width:100%; height:40rem; background-color:#f4f4f4">
                <div class="no-image-massage"> 
                    No Image Available
                </div>
            </div>
        <% end %>
    </div>
    <div class= "col-xs-12 col-md-5 ">
        <h2 class="center"><%= @auction.name %></h2>
        <h3>STARTING BID: <%= @auction.starting_bid %> &#x20B9; <br> CURRENT PRICE: <%= @auction.current_price %> &#x20B9;</h3> 
        
        <h3>Description</h3>
        <p><%= @auction.description%></p>
        
        <h3>
            <% if in_progress?(@auction.id) %> 
                Auction ends in: <strong><%= time_ago_in_words(@auction.deadline) %></strong>
            <% else %>
                Deadline was: <%= @auction.deadline.strftime("%B %d, %Y | %l:%M %p") %>
            <% end %>
        </h3>
        <br>
        
        <% if user_signed_in? && current_user == @auction.user %>
            <%= link_to 'Edit the Details', edit_auction_path, class:"btn btn-sm btn-primary " %>
            <%= link_to 'Delete the product', auction_path(@auction), method: :delete, data:{confirm: "Are you sure?"}, class:"btn btn-sm btn-danger" %>
            <%= link_to 'Back to User Dashboard', user_path(current_user), class:"btn btn-sm btn-default" %>
            <%= link_to 'Back', :back, class:"btn btn-sm btn-default " %>
        <% end %>

        <% if @auction.user != current_user %>
            <%= link_to 'Back to Home', auctions_path, class:"btn btn-sm btn-success" %>
            <%= link_to 'Bid Now', new_bid_path(:id => @auction.id), class:"btn btn-sm btn-success" %>
            <%= link_to 'Back', :back, class:"btn btn-sm btn-default " %>
        <% end %><br>
        <small>last updated: <%= time_ago_in_words(@auction.updated_at) %> ago </small>
    </div>
</div>
<div>
    <p>Seller Details </p>
    <h2><%= link_to @auction.user.full_name, @auction.user == current_user && user_signed_in? ? user_path(@auction.user) : '#'%></h2>
    <small> 
        joined Online-Auction: <%= time_ago_in_words(@auction.user.created_at)%> ago,
        last updated: <%= time_ago_in_words(@auction.user.updated_at) %> ago 
    </small>
    
    <h3>email address</h3>
    <p><%= @auction.user.email%></p>

    <h3>contact number</h3>
    <p><%= @auction.user.contact_number%></p>
    
    <h3>address</h3>
    <p><%= @auction.user.address%></p>
</div>