config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  
  resources :searches
  resources :auctions
  resources :auctions do
    member do
      patch 'claim'
    end
  end

  root 'auctions#index'
  # patch '/auctions/:id/claim', to: 'auctions#claim'

  resources :users, only: [:index, :show]
  get 'claimed', to: 'users#claimed'
  get 'sold', to: 'users#sold'

  resources :bids, only: [:index, :new, :create]
  get 'cart', to: 'bids#cart'
  
  # get 'show', to: 'users#show'
  # get 'index', to: 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="footer-content">
        QBid is a leading online auction platform, connecting buyers and sellers globally. 
        <br>Our goal is to provide a secure and transparent bidding experience for everyone.
    </div>
    <hr style = "border-color:#3f414d">
    <div>
        <a href="https://github.com/mpatel2280" target="_blank">
            <%= image_tag(asset_url("github.png"), class:"footer-icons") %>
        </a>
        <a href="https://www.linkedin.com/in/manishlinkedin" target="_blank">
            <%= image_tag(asset_url("linkedin.png"), class:"footer-icons") %>
        </a>
        <a href="https://www.instagram.com/" target="_blank"> 
            <%= image_tag(asset_url("instagram.png"), class:"footer-icons") %>
        </a>
        <a href="https://www.facebook.com/profile.php?id=XXXXXXXXXX" target="_blank">
            <%= image_tag(asset_url("facebook.png"), class:"footer-icons") %>
        </a>
        <span class="footer-item">Copyright &copy;2024 All rights reserved</span>
    </div>
</div>
<%# class="footer-item " %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'QBid', root_path, class:"navbar-brand", id:"logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Dashboard',auctions_path %></li>

          <li>
            <%= link_to new_search_path do %>
              <i class="fa fa-search" aria-hidden="true"></i> search
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Bike', "#", id:"droplist" %></a></li>
              <li><%= link_to 'Furniture', "#", id:"droplist" %></li>
              <li><%= link_to 'Toys', "#", id:"droplist" %></li>             
              <li role="separator" class="divider"></li>
              <li><%= link_to 'User List', users_path, id:"droplist" %></li>
            </ul>
          </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to image_tag(asset_url("cart2.png")), cart_path, id: "cart-logo" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> <%= current_user.full_name.present? ? current_user.full_name : current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Add Products', new_auction_path, id:"droplist" %></li>
              <li><%= link_to 'your products', user_path(current_user), id:"droplist" %></li>
              <li><%= link_to 'sold products', sold_path,id:"droplist" %></li>
              <li><%= link_to 'Claimed products', claimed_path, id:"droplist"%></li>

              <li><%= link_to 'Edit User', edit_user_registration_path(current_user), id:"droplist" %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Delete Account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete, id: "droplist" %></li>
            </ul>
          </li>
          <li><%= link_to 'Log out', destroy_user_session_path,method: :delete, class:"btn btn-danger", id:"logout-btn" %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path, class:"btn btn-primary", id:"login-btn" %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path, style:"padding: 1.5rem 4rem" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QBid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render 'layouts/navigation'%>
    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer'%>
  </body>
</html>